// <auto-generated />
using System;

using DatacomTest.Api.Repositories;

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatacomTest.Api.Migrations {
	[DbContext(typeof(JobApplicationDbContext))]
	partial class JobApplicationDbContextModelSnapshot : ModelSnapshot {
		protected override void BuildModel(ModelBuilder modelBuilder) {
// Disable warnings for deprecated EF Core API usage (warnings 612 and 618)
#pragma warning disable 612, 618
			modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

			modelBuilder.Entity(
				"DatacomTest.Api.Models.JobApplication",
				b => {
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("INTEGER");

					b.Property<string>("CompanyName")
						.IsRequired()
						.HasMaxLength(200)
						.HasColumnType("TEXT");

					b.Property<DateOnly>("DateApplied")
						.HasColumnType("TEXT");

					b.Property<string>("Position")
						.IsRequired()
						.HasMaxLength(200)
						.HasColumnType("TEXT");

					b.Property<int>("Status")
						.HasColumnType("INTEGER");

					b.HasKey("Id");

					b.ToTable("JobApplications");
				}
			);
#pragma warning restore 612, 618
		}
	}
}
